<?php
/**
 * Implementation of hook_init().
 *
 * Load required includes.
 */
function audiofield_init() {
  // If FileField is not available, immediately disable audiofield.
  if (!module_exists('filefield')) {
    module_disable(array('audiofield'));
    drupal_set_message(t('The audiofield module has been disabled. The <a href="http://drupal.org/project/filefield">FileField module</a> needs to be installed for it to work properly.'));
    return;
  }
  module_load_include('inc', 'audiofield', 'audiofield_widget');
}
/**
 * Implementation of hook_menu().
 */
function audiofield_menu() {
  
  $items['admin/settings/audiofield'] = array(
    'title' => 'Audio Field',
    'description' => 'Configure audiofield.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('audiofield_admin_settings_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
      return $items;
}

function audiofield_admin_settings_form() {
  global $base_path;
  
  if (variable_get('audiofield_extension', 'mp3')=="") {
    variable_set('audiofield_extension', 'mp3' ); 
  }
  $form['audiofield_extension'] = array(
    '#type' => 'textfield',
    '#title' => t('Audio Extension'),
    '#description' => t('Enter the audio extension seperated by coma , By default, the audio extension is mp3 '),
    '#default_value' => variable_get('audiofield_extension', 'mp3')
  );
  
  if (variable_get('audiofield_maximum_size', '50' )=="") {
    variable_set('audiofield_maximum_size', '50' );
  }
  
  $form['audiofield_maximum_size']=array(
    '#type' => 'textfield',
    '#title' => t('The Maximume size'),
    '#description' => t(' The maximum size is ' . variable_get('audiofield_maximum_size', '50') . ', By defult 50 MB.'),
    '#default_value' => variable_get('audiofield_maximum_size', '50' )
  );
  
    $player1=realpath("sites") . "/all/libraries/player/audio-player/player.swf";
    $player2=realpath("sites") . "/all/libraries/player/xspf_player_slim.swf";
    $player3=realpath("sites") . "/all/libraries/player/playerSinglePackage/playerSingle.swf";
    
    $palyers=array();
    if (file_exists($player1)) {
          $players[]='<object id="audioplayer2" height="24" width="290" data="' . $base_path . 'sites/all/libraries/player/audio-player/player.swf" type="application/x-shockwave-flash">
                          <param value="' . $base_path . 'sites/all/libraries/player/audio-player/player.swf" name="movie"/>
                          <param value="playerID=2&bg=0xCDDFF3&leftbg=0x357DCE&lefticon=0xF2F2F2&rightbg=0xF06A51&rightbghover=0xAF2910&righticon=0xF2F2F2&righticonhover=0xFFFFFF&text=0x357DCE&slider=0x357DCE&track=0xFFFFFF&border=0xFFFFFF&loader=0xAF2910&soundFile=' . $base_path . 'sites/all/libraries/player/Sample_Track.mp3" name="FlashVars"/>
                          <param value="high" name="quality"/>
                          <param value="false" name="menu"/>
                          <param value="#FFFFFF" name="bgcolor"/>
                          </object>';
  
          $players[]='<object id="audioplayer1" height="24" width="290" data="' . $base_path . 'sites/all/libraries/player/audio-player/player.swf" type="application/x-shockwave-flash">
                          <param value="' . $base_path . 'sites/all/libraries/player/audio-player/player.swf" name="movie"/>
                          <param value="playerID=1&bg=0xf8f8f8&leftbg=0xeeeeee&lefticon=0x666666&rightbg=0xcccccc&rightbghover=0x999999&righticon=0x666666&righticonhover=0xFFFFFF&text=0x666666&slider=0x666666&track=0xFFFFFF&border=0x666666&loader=0x9FFFB8&soundFile=' . $base_path . 'sites/all/libraries/player/Sample_Track.mp3" name="FlashVars"/>
                          <param value="high" name="quality"/>
                          <param value="false" name="menu"/>
                          <param value="#FFFFFF" name="bgcolor"/>
                          </object>';
                          }
    if (file_exists($player2)) {
      $players[]='<object type="application/x-shockwave-flash" width="175" height="14"
                    data="' . $base_path . 'sites/all/libraries/player/xspf_player_slim.swf?song_url=' . $base_path . 'sites/all/libraries/player/Sample_Track.mp3">
                    <param name="movie" value="' . $base_path . 'sites/all/libraries/player/xspf_player_slim.swf?song_url=' . $base_path .'sites/all/libraries/player/Sample_Track.mp3" />
                    </object>';
    }
    if (file_exists($player3)) {
      $players[]='<object >
                          <param name="autoplay" value="true" />
                          <param name="controller"value="true" /> 
                          <embed src="' . $base_path . 'sites/all/libraries/player/playerSinglePackage/playerSingle.swf"  width="175" height="80" float="left" wmode="transparent" flashvars="soundPath=' . $base_path .'sites/all/libraries/player/Sample_Track.mp3" autostart="true" loop="false"  controller="true" bgcolor="#FF9900" pluginspage="http://www.macromedia.com/go/getflashplayer" >
                          </embed>
                          </object>';
    }
    $form['audiofield_audioplayer'] = array(
      '#type' => 'radios',
      '#title' => t('Audio Player'),
      '#options' => $players,
      '#default_value' => variable_get('audiofield_audioplayer', '0')
    );
    
    $form['#validate'][] ="_uc_return_order_validate";
    
    return system_settings_form($form);
}


/**
 * Implementation of hook_elements().
 */
function audiofield_elements() {
  $elements = array();
  $filefield_elements = filefield_elements();
  $elements['audiofield_widget'] = $filefield_elements['filefield_widget'];

  $elements['audiofield_widget']['#value_callback'] = 'audiofield_widget_value';
  return $elements;
}

/**
 * Implementation of hook_theme().
 */
function audiofield_theme() {
  $theme= array(
      // Theme an image uploaded to audiofield with alt and title.
      'audiofield_widget' => array(
      'arguments' => array('element' => NULL),
      'file' => 'audiofield_widget.inc',
      ),
      'audiofield_widget_item' => array(
      'arguments' => array('element' => NULL),
      'file' => 'audiofield_widget.inc',
      ),
      'audiofield_widget_preview' => array(
      'arguments' => array('element' => NULL),
      'file' => 'audiofield_widget.inc',
      ),
      'audiofield_widget_file' => array(
      'arguments' => array('element' => NULL),
      'file' => 'audiofield_widget.inc',
      ),
      'audiofield_item' => array(
      'arguments' => array('file' => NULL, 'field' => NULL),
      'file' => 'audiofield_formatter.inc',
      ),
      'audiofield_file' => array(
      'arguments' => array('file' => NULL),
      'file' => 'audiofield_formatter.inc',
      ),
      // Themes for the formatters.
      'audiofield_formatter_audiofield_embedded' => array(
      'arguments' => array('element' => NULL),
      'file' => 'audiofield_formatter.inc',
      ),
  );

  return $theme;
}

function audiofield_widget_info() {
  return array(
    'audiofield_widget' => array(
      'label' => t('Audio Upload'),
      'field types' => array('filefield'),
      'multiple values' => CONTENT_HANDLE_CORE,
      'callbacks' => array('default value' => CONTENT_CALLBACK_CUSTOM),
      'description' => t('Widget for uploading audios.'),
    ),
  );
}

/**
 * Implementation of CCK's hook_widget_settings().
 */
function audiofield_widget_settings($op, $widget) {
  switch ($op) {
    case 'form':
      return audiofield_widget_settings_form($widget);
    case 'save':
      return audiofield_widget_settings_save($widget);
  }
}

/**
 * Implementation of CCK's hook_widget().
 * 
 * Assign default properties to item and delegate to audiofield.
 */
function audiofield_widget(&$form, &$form_state, $field, $items, $delta = 0) {
  // Start with the audiofield widget as a basic start.
  // Note that audiofield needs to modify $form by reference.
  $element = filefield_widget($form, $form_state, $field, $items, $delta);

  return $element;
}


//==========================================//
// DEFINING A FORMATTER
//==========================================//


/**
 * Implementation of hook_field_formatter_info().
 *   
 * All fields should have a 'default' formatter.
 * Any number of other formatters can be defined as well.
 * It's nice for there always to be a 'plain' option
 * for the raw value, but that is not required.
 * 
 */
function audiofield_field_formatter_info() {
  $formatters = array(
    'audiofield_embedded' => array(
      'label' => t('audiofield embedded'),
      'field types' => array('filefield'),
      'description' => t('Displays audio embedded in a web page.'),
    ),
  );

  return $formatters;
}


/**
 * Implementation of CCK's hook_default_value().
 */
function audiofield_default_value(&$form, &$form_state, $field, $delta) {
  return filefield_default_value($form, $form_state, $field, $delta);
}

/**
 * Implementation of hook_form_[form_id]_alter().
 *
 * Modify the add new field form to change the default formatter.
 */
function audiofield_form_content_field_overview_form_alter(&$form, &$form_state) {
  $form['#submit'][] = 'audiofield_form_content_field_overview_submit';
}

/**
 * Submit handler to set a new field's formatter to "audiofield_embedded".
 */
function audiofield_form_content_field_overview_submit(&$form, &$form_state) {
  if (isset($form_state['fields_added']['_add_new_field']) && isset($form['#type_name'])) {
    $new_field = $form_state['fields_added']['_add_new_field'];
    $node_type = $form['#type_name'];
    $field = content_fields($new_field, $node_type);
    if ($field['widget']['module'] == 'audiofield') {
      foreach ($field['display_settings'] as $display_type => $display_settings) {
        if ($field['display_settings'][$display_type]['format'] == 'default') {
          $field['display_settings'][$display_type]['format'] = 'audiofield_embedded';
        }
      }
      content_field_instance_update($field);
    }
  }
}